# Automatically generated by Matugen

export MAT_PRIMARY="#afc6ff"
export MAT_ON_PRIMARY="#132f60"

export MAT_SECONDARY="#bfc6dc"
export MAT_ON_SECONDARY="#293042"

export MAT_TERTIARY="#dfbbde"
export MAT_ON_TERTIARY="#402743"

export MAT_BACKGROUND="#121318"
export MAT_ON_BACKGROUND="#e2e2e9"

export MAT_SURFACE="#121318"
export MAT_ON_SURFACE="#e2e2e9"

export MAT_OUTLINE="#8f9099"
export MAT_OUTLINE_VARIANT="#44464f"

export MAT_ERROR="#ffb4ab"
export MAT_ON_ERROR="#690005"

