# Automatically generated by Matugen

export MAT_PRIMARY="{{colors.primary.default.hex}}"
export MAT_ON_PRIMARY="{{colors.on_primary.default.hex}}"

export MAT_SECONDARY="{{colors.secondary.default.hex}}"
export MAT_ON_SECONDARY="{{colors.on_secondary.default.hex}}"

export MAT_TERTIARY="{{colors.tertiary.default.hex}}"
export MAT_ON_TERTIARY="{{colors.on_tertiary.default.hex}}"

export MAT_BACKGROUND="{{colors.background.default.hex}}"
export MAT_ON_BACKGROUND="{{colors.on_background.default.hex}}"

export MAT_SURFACE="{{colors.surface.default.hex}}"
export MAT_ON_SURFACE="{{colors.on_surface.default.hex}}"

export MAT_OUTLINE="{{colors.outline.default.hex}}"
export MAT_OUTLINE_VARIANT="{{colors.outline_variant.default.hex}}"

export MAT_ERROR="{{colors.error.default.hex}}"
export MAT_ON_ERROR="{{colors.on_error.default.hex}}"

